[toolchain]

[features]
seeds = false
skip-lint = false

[test]
startup_wait = 10000

[programs.localnet]
token_22_staking = "GagRxsRHtWh3ZvPyBnbjsEakek3isoKxFGdHgXQhwBpE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/elpis/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
